version: '3.7'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db
  ui:
#    build: ./ui
    image: ${USERNAME}/ui
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
  post:
#    build: ./post-py
    image: ${USERNAME}/post
    networks:
      - reddit
  comment:
#    build: ./comment
    image: ${USERNAME}/comment
    networks:
      - reddit
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - reddit 

volumes:
  post_db:

networks:
  reddit:
    